language: go

sudo: false

os:
- linux
- osx

go:
- 1.11.x

install:
# - make deps

script:
- make build

before_deploy:
- mkdir -p build
- tar czvf build/meshbird-$TRAVIS_TAG.$TRAVIS_OS_NAME-amd64.tar.gz bin/meshbird

deploy:
- provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
  - build/meshbird-$TRAVIS_TAG.linux-amd64.tar.gz
  - build/meshbird-$TRAVIS_TAG.osx-amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
